[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-solver"
version = "1.0.0"
description = "MCP server for constraint solving"
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "minizinc",
]

[project.scripts]
mcp-solver = "mcp_solver.server:main"

[tool.black]
line-length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
